### ISSUE TITLE
pulseciravg fails for avg_size = 1

### ISSUE THREAD

**Issue by samprager** [samprager/fpga#4]
New test case added to test bench for avg_size=1. The block fails to output any data in this case. Fix will probably require adding a special case to handle this in the HLS state machine source code -- ie. if avg_size =1, just pass the data through without storing in fifo.

**Comment by sarinaka** [comment]
Hi Sam!

Since you're working on the lab computer right now, I can address the issue
you just posted on the wiki, after the meeting today. Is that alright? I
don't want to interfere with any work you have.

Thanks,
Sarina
